defaults:
  - defaults.yaml

project: "federated-flwr"
run_id: ""
checkpoint_path: ""
resume: False
start_round: 0

training:
  per_device_train_batch_size: 2
  logging_dir: "./logs"
  logging_steps: 10
  max_seq_length: 2048
  num_train_epochs: 1
  eval_strategy: "steps"
  eval_on_start: True
  report_to: "none"
  save_strategy: "no"
  dataset_text_field: "text"
  warmup_ratio: 0.05
  batch_eval_metrics: True
  learning_rate: 5E-04

evaluation:
  output_dir: "./results"
  per_device_eval_batch_size: 8
