defaults:
  - defaults.yaml

project: "federated-flwr"
run_id: ""
checkpoint_path: ""
resume: False

training:
  per_device_train_batch_size: 8
  logging_dir: "./logs"
  logging_steps: 10
  max_seq_length: 512
  num_train_epochs: 4
  evaluation_strategy: "steps"
  eval_on_start: True
  eval_steps: 1000 # Evaluate every 10 steps
  report_to: "none"
  dataset_text_field: "text"
  batch_eval_metrics: True
  learning_rate: 5E-04
  save_strategy : "best"
  load_best_model_at_end: True
  save_total_limit: 2
  metric_for_best_model: "eval_rouge1"


evaluation:
  output_dir: "./results"
  per_device_eval_batch_size: $training.per_device_train_batch_size

